[package]
name = "monokrom"
version = "0.1.0"
edition = "2021"
description = "A fantasy console text editor"

[dependencies]
macroquad = "0.4"
ropey = "1.6"
logos = "0.14"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
arboard = "3.2"
directories = "5.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
quad-storage = "0.1"
sapp-jsutils = "0.1"
